services:
  iso-builder-x86_64:
    build:
      context: .
      dockerfile: x86_64/Dockerfile
    container_name: archetype-iso-builder-x86_64
    privileged: true
    volumes:
      - ./output:/output
      - ./scripts:/build/scripts:ro
    environment:
      - TZ=Europe/Rome
      - ARCH=x86_64

  iso-builder-arm64:
    build:
      context: .
      dockerfile: arm64/Dockerfile
    container_name: archetype-iso-builder-arm64
    privileged: true
    volumes:
      - ./output:/output
      - ./scripts:/build/scripts:ro
    environment:
      - TZ=Europe/Rome
      - ARCH=aarch64
    platform: linux/arm64
