services:
  iso-builder-x86_64:
    build:
      context: .
      dockerfile: x86_64/Dockerfile
    container_name: archetype-iso-builder-x86_64
    privileged: true
    volumes:
      - ./output:/output
      - ./scripts:/build/scripts:ro
    environment:
      - TZ=Europe/Rome
      - ARCH=x86_64

  iso-builder-arm64:
    image: alpine:3.22
    container_name: archetype-iso-builder-arm64
    platform: linux/arm64
    volumes:
      - ./arm64:/build
    working_dir: /build
    command: >
      sh -c "apk add --no-cache bash xorriso curl wget &&
             chmod +x /build/build-iso.sh &&
             /build/build-iso.sh"
    environment:
      - TZ=Europe/Rome
