---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 20Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: database
spec:
  schedule: "0 2 * * *"  # 2 AM every day
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: postgres:15-alpine
            env:
            - name: PGHOST
              value: "patroni"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: patroni-secrets
                  key: PATRONI_SUPERUSER_PASSWORD
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting PostgreSQL backup..."
              pg_dumpall | gzip > /backup/backup-$(date +%Y%m%d-%H%M%S).sql.gz
              # Keep only last 7 days
              find /backup -name "backup-*.sql.gz" -mtime +7 -delete
              echo "Backup completed: $(ls -lh /backup | tail -1)"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
